apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xki8i29bf-java-quarkus
  janus-idp.io/tekton: xki8i29bf-java-quarkus
  backstage.io/kubernetes-id: xki8i29bf-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xki8i29bf-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
